-- Seed idempotente: re-executavel em qualquer ambiente.
-- O guard 'where not exists' existe porque este arquivo roda no pipeline
-- (preview e producao) e um insert simples duplicaria a cada deploy.

-- Seed: catálogo de alimentos
--
-- Macros por 100 g, salvo quando `serving_size` diz outra coisa.
-- Fonte de referência: TACO (Tabela Brasileira de Composição de Alimentos).
--
-- Toda linha nasce categorizada. O vocabulário é fechado por CHECK na 0047, e
-- alimento sem categoria é alimento que a busca por "proteínas" não acha —
-- pior que não filtrar, porque a lista incompleta parece completa.

insert into foods (name, category, calories, protein, carbs, fat, fiber, serving_size)
select v.name, v.category, v.calories, v.protein, v.carbs, v.fat, v.fiber, v.serving_size
from (values
-- Proteínas animais
('Frango (peito grelhado)',           'proteina',   159, 32.0, 0.0,  2.7,  0.0,  100),
('Frango (coxa sem pele assada)',     'proteina',   195, 26.9, 0.0,  9.3,  0.0,  100),
('Frango (sobrecoxa assada)',         'proteina',   215, 25.0, 0.0,  12.5, 0.0,  100),
('Frango desfiado cozido',            'proteina',   163, 30.0, 0.0,  4.0,  0.0,  100),
('Peito de peru defumado',            'proteina',   100, 18.0, 2.0,  2.0,  0.0,  100),
('Presunto magro',                    'proteina',   121, 17.0, 1.0,  5.0,  0.0,  100),
('Carne bovina (patinho)',            'proteina',   219, 28.0, 0.0,  11.6, 0.0,  100),
('Carne bovina (alcatra)',            'proteina',   241, 26.0, 0.0,  14.7, 0.0,  100),
('Carne bovina (coxão mole)',         'proteina',   219, 32.4, 0.0,  8.8,  0.0,  100),
('Carne bovina (músculo cozido)',     'proteina',   191, 30.0, 0.0,  7.4,  0.0,  100),
('Carne moída (patinho)',             'proteina',   212, 26.7, 0.0,  11.0, 0.0,  100),
('Carne suína (lombo assado)',        'proteina',   210, 32.0, 0.0,  8.4,  0.0,  100),
('Fígado bovino grelhado',            'proteina',   225, 29.9, 3.1,  9.4,  0.0,  100),
('Ovo inteiro cozido',                'proteina',   146, 13.0, 0.6,  9.9,  0.0,  50),
('Clara de ovo',                      'proteina',   48,  11.1, 0.7,  0.2,  0.0,  30),
('Ovo de codorna cozido',             'proteina',   158, 13.7, 0.8,  11.0, 0.0,  50),
('Atum em água (lata)',               'proteina',   109, 24.4, 0.0,  0.9,  0.0,  130),
('Atum fresco grelhado',              'proteina',   184, 29.9, 0.0,  6.3,  0.0,  100),
('Salmão grelhado',                   'proteina',   208, 28.0, 0.0,  10.0, 0.0,  100),
('Tilápia grelhada',                  'proteina',   128, 26.0, 0.0,  2.7,  0.0,  100),
('Merluza grelhada',                  'proteina',   122, 26.0, 0.0,  1.8,  0.0,  100),
('Pescada grelhada',                  'proteina',   128, 26.0, 0.0,  2.5,  0.0,  100),
('Bacalhau dessalgado cozido',        'proteina',   138, 29.0, 0.0,  1.5,  0.0,  100),
('Sardinha (lata, drenada)',          'proteina',   208, 24.6, 0.0,  11.5, 0.0,  100),
('Camarão cozido',                    'proteina',   90,  20.0, 0.0,  1.0,  0.0,  100),
('Tofu',                              'proteina',   76,  8.1,  1.9,  4.8,  0.3,  100),
('Seitan',                            'proteina',   141, 25.0, 4.0,  2.0,  0.6,  100),
('Proteína de soja texturizada',      'proteina',   336, 51.0, 31.0, 1.2,  20.0, 50),

-- Laticínios
('Leite desnatado',                   'laticinio',  35,  3.4,  4.9,  0.2,  0.0,  200),
('Leite integral',                    'laticinio',  61,  3.2,  4.7,  3.3,  0.0,  200),
('Leite sem lactose desnatado',       'laticinio',  35,  3.3,  4.9,  0.2,  0.0,  200),
('Iogurte natural desnatado',         'laticinio',  41,  4.1,  4.7,  0.2,  0.0,  170),
('Iogurte natural integral',          'laticinio',  70,  4.1,  5.2,  3.5,  0.0,  170),
('Iogurte grego natural',             'laticinio',  97,  9.0,  4.0,  5.0,  0.0,  130),
('Iogurte grego zero',                'laticinio',  59,  10.0, 4.0,  0.2,  0.0,  130),
('Kefir de leite',                    'laticinio',  55,  3.3,  4.5,  3.0,  0.0,  200),
('Queijo cottage',                    'laticinio',  98,  11.1, 3.4,  4.3,  0.0,  100),
('Queijo minas frescal',              'laticinio',  264, 17.4, 3.2,  20.2, 0.0,  50),
('Queijo muçarela',                   'laticinio',  330, 22.6, 3.0,  25.2, 0.0,  30),
('Queijo parmesão',                   'laticinio',  453, 35.6, 1.7,  33.5, 0.0,  20),
('Ricota',                            'laticinio',  140, 12.6, 3.8,  8.1,  0.0,  50),
('Requeijão light',                   'laticinio',  175, 9.0,  4.0,  13.0, 0.0,  30),
('Bebida de amêndoas sem açúcar',     'laticinio',  15,  0.5,  0.6,  1.2,  0.3,  200),
('Bebida de soja sem açúcar',         'laticinio',  41,  3.3,  1.0,  2.1,  0.6,  200),

-- Carboidratos
('Arroz branco cozido',               'carboidrato', 128, 2.5, 28.1, 0.2,  1.6,  100),
('Arroz integral cozido',             'carboidrato', 124, 2.6, 25.8, 1.0,  2.7,  100),
('Arroz parboilizado cozido',         'carboidrato', 123, 2.5, 25.8, 0.5,  1.6,  100),
('Arroz sete grãos cozido',           'carboidrato', 130, 3.5, 26.0, 1.0,  2.5,  100),
('Macarrão cozido',                   'carboidrato', 157, 5.8, 30.9, 1.3,  1.8,  100),
('Macarrão integral cozido',          'carboidrato', 124, 5.0, 25.0, 0.9,  3.0,  100),
('Batata doce cozida',                'carboidrato', 77,  0.6, 18.4, 0.1,  2.2,  100),
('Batata doce roxa cozida',           'carboidrato', 77,  0.6, 18.4, 0.1,  2.6,  100),
('Batata inglesa cozida',             'carboidrato', 52,  1.2, 11.9, 0.1,  1.3,  100),
('Batata baroa cozida',               'carboidrato', 80,  1.0, 18.9, 0.2,  2.1,  100),
('Mandioca cozida',                   'carboidrato', 125, 0.6, 30.1, 0.3,  1.6,  100),
('Inhame cozido',                     'carboidrato', 97,  2.1, 22.5, 0.1,  1.7,  100),
('Cará cozido',                       'carboidrato', 100, 2.0, 23.0, 0.2,  1.5,  100),
('Milho verde cozido',                'carboidrato', 98,  3.2, 20.0, 1.0,  3.9,  100),
('Polenta cozida',                    'carboidrato', 90,  2.0, 19.0, 0.5,  1.0,  100),
('Pão francês',                       'carboidrato', 300, 8.0, 58.6, 3.1,  2.3,  50),
('Pão integral',                      'carboidrato', 253, 9.4, 43.9, 3.7,  5.9,  50),
('Pão de forma integral',             'carboidrato', 253, 9.4, 43.9, 3.7,  5.9,  50),
('Pão sírio integral',                'carboidrato', 275, 9.0, 55.0, 1.5,  4.0,  60),
('Pão de queijo',                     'carboidrato', 363, 5.0, 40.0, 20.0, 1.0,  40),
('Torrada integral',                  'carboidrato', 371, 12.0, 66.0, 6.0, 7.0,  30),
('Biscoito de arroz',                 'carboidrato', 387, 8.0, 82.0, 3.0,  2.0,  20),
('Aveia em flocos',                   'carboidrato', 394, 13.9, 66.6, 8.5, 9.1,  30),
('Farinha de aveia',                  'carboidrato', 394, 14.0, 67.0, 8.0, 9.1,  30),
('Granola sem açúcar',                'carboidrato', 425, 10.0, 65.0, 13.0, 8.0, 40),
('Tapioca (goma)',                    'carboidrato', 350, 0.0, 87.0, 0.0,  0.0,  50),
('Crepioca',                          'carboidrato', 180, 9.0, 22.0, 6.0,  0.5,  100),
('Cuscuz de milho',                   'carboidrato', 113, 2.4, 25.3, 0.5,  1.6,  100),
('Cuscuz marroquino cozido',          'carboidrato', 112, 3.8, 23.2, 0.2,  1.4,  100),
('Quinoa cozida',                     'carboidrato', 120, 4.4, 21.3, 1.9,  2.8,  100),
('Panqueca de aveia',                 'carboidrato', 210, 12.0, 24.0, 7.0, 3.0,  100),

-- Leguminosas
('Feijão carioca cozido',             'leguminosa', 76,  4.8,  13.6, 0.5,  8.4,  100),
('Feijão preto cozido',               'leguminosa', 77,  5.1,  14.0, 0.5,  8.7,  100),
('Feijão branco cozido',              'leguminosa', 91,  6.0,  16.0, 0.5,  6.0,  100),
('Feijão fradinho cozido',            'leguminosa', 78,  4.6,  13.5, 0.5,  5.0,  100),
('Feijão azuki cozido',               'leguminosa', 128, 7.5,  25.0, 0.1,  7.3,  100),
('Lentilha cozida',                   'leguminosa', 116, 9.0,  20.1, 0.4,  7.9,  100),
('Grão de bico cozido',               'leguminosa', 164, 8.9,  27.4, 2.6,  7.6,  100),
('Ervilha cozida',                    'leguminosa', 81,  5.4,  14.5, 0.4,  5.1,  100),
('Soja cozida',                       'leguminosa', 172, 16.6, 9.9,  9.0,  6.0,  100),
('Edamame',                           'leguminosa', 122, 11.9, 8.9,  5.2,  5.2,  100),
('Tremoço em conserva',               'leguminosa', 119, 15.6, 9.9,  2.9,  2.8,  100),
('Homus',                             'leguminosa', 166, 7.9,  14.3, 9.6,  6.0,  50),

-- Gorduras boas
('Azeite de oliva',                   'gordura',    884, 0.0,  0.0,  100.0, 0.0, 10),
('Óleo de coco',                      'gordura',    862, 0.0,  0.0,  100.0, 0.0, 10),
('Óleo de canola',                    'gordura',    884, 0.0,  0.0,  100.0, 0.0, 10),
('Manteiga',                          'gordura',    717, 0.9,  0.1,  81.1, 0.0,  10),
('Manteiga ghee',                     'gordura',    876, 0.3,  0.0,  99.5, 0.0,  10),
('Castanha do Pará',                  'gordura',    643, 14.5, 15.1, 63.5, 7.9,  30),
('Castanha de caju',                  'gordura',    570, 18.5, 29.1, 46.3, 3.7,  30),
('Amêndoas',                          'gordura',    579, 21.2, 21.6, 49.9, 12.5, 30),
('Nozes',                             'gordura',    654, 15.2, 13.7, 65.2, 6.7,  30),
('Avelã',                             'gordura',    628, 15.0, 16.7, 60.8, 9.7,  30),
('Amendoim',                          'gordura',    544, 27.2, 20.3, 43.9, 8.0,  30),
('Pasta de amendoim',                 'gordura',    588, 25.0, 20.0, 50.0, 6.0,  20),
('Semente de girassol',               'gordura',    584, 20.8, 20.0, 51.5, 8.6,  20),
('Semente de abóbora',                'gordura',    559, 30.2, 10.7, 49.1, 6.0,  20),
('Gergelim',                          'gordura',    573, 17.7, 23.4, 49.7, 11.8, 15),
('Chia',                              'gordura',    486, 16.5, 42.1, 30.7, 34.4, 15),
('Linhaça',                           'gordura',    495, 14.1, 43.3, 32.3, 33.5, 15),
('Coco fresco',                       'gordura',    354, 3.3,  15.2, 33.5, 9.0,  30),
('Azeitona verde',                    'gordura',    145, 1.0,  3.8,  15.3, 3.3,  30),

-- Frutas
('Abacate',                           'fruta',      160, 2.0,  8.5,  14.7, 6.7,  100),
('Banana prata',                      'fruta',      98,  1.3,  26.0, 0.1,  2.0,  100),
('Banana nanica',                     'fruta',      92,  1.4,  23.8, 0.1,  1.9,  100),
('Maçã',                              'fruta',      56,  0.3,  15.2, 0.0,  1.3,  100),
('Pera',                              'fruta',      53,  0.6,  14.0, 0.1,  3.0,  100),
('Mamão',                             'fruta',      45,  0.8,  11.6, 0.1,  1.8,  100),
('Laranja',                           'fruta',      45,  1.0,  11.5, 0.1,  0.8,  100),
('Tangerina',                         'fruta',      58,  0.8,  14.0, 0.1,  1.7,  100),
('Limão',                             'fruta',      22,  0.9,  11.1, 0.1,  2.8,  100),
('Morango',                           'fruta',      32,  0.7,  7.7,  0.3,  2.0,  100),
('Mirtilo',                           'fruta',      57,  0.7,  14.5, 0.3,  2.4,  100),
('Framboesa',                         'fruta',      52,  1.2,  11.9, 0.7,  6.5,  100),
('Uva',                               'fruta',      69,  0.6,  18.1, 0.2,  0.9,  100),
('Abacaxi',                           'fruta',      48,  0.9,  12.3, 0.1,  1.0,  100),
('Manga',                             'fruta',      64,  0.4,  16.7, 0.2,  1.6,  100),
('Melancia',                          'fruta',      33,  0.9,  8.1,  0.0,  0.1,  100),
('Melão',                             'fruta',      29,  0.7,  7.5,  0.0,  0.3,  100),
('Kiwi',                              'fruta',      51,  1.3,  11.5, 0.6,  2.7,  100),
('Goiaba',                            'fruta',      54,  1.1,  13.0, 0.4,  6.2,  100),
('Ameixa',                            'fruta',      53,  0.8,  13.9, 0.0,  2.4,  100),
('Caqui',                             'fruta',      71,  0.4,  19.3, 0.1,  6.5,  100),
('Maracujá',                          'fruta',      68,  2.0,  12.3, 0.4,  1.1,  100),
('Açaí (polpa sem açúcar)',           'fruta',      58,  0.8,  6.2,  3.9,  2.6,  100),
('Uva passa',                         'fruta',      299, 3.1,  79.2, 0.5,  3.7,  30),
('Damasco seco',                      'fruta',      241, 3.4,  63.0, 0.5,  7.3,  30),
('Tâmara',                            'fruta',      282, 2.5,  75.0, 0.4,  8.0,  30),
('Banana passa',                      'fruta',      318, 3.9,  79.0, 1.0,  5.0,  30),

-- Hortaliças
('Brócolis cozido',                   'hortalica',  25,  2.1,  4.4,  0.5,  3.4,  100),
('Couve-flor cozida',                 'hortalica',  23,  1.9,  4.5,  0.2,  2.4,  100),
('Repolho cru',                       'hortalica',  25,  1.3,  5.8,  0.1,  2.5,  100),
('Couve refogada',                    'hortalica',  90,  2.8,  5.5,  6.6,  3.1,  100),
('Espinafre',                         'hortalica',  23,  2.9,  3.6,  0.4,  2.2,  100),
('Rúcula',                            'hortalica',  25,  2.6,  3.7,  0.4,  1.6,  100),
('Agrião',                            'hortalica',  17,  2.3,  2.3,  0.1,  2.1,  100),
('Alface',                            'hortalica',  15,  1.4,  2.9,  0.2,  1.3,  100),
('Tomate',                            'hortalica',  15,  1.1,  3.1,  0.2,  1.2,  100),
('Pepino',                            'hortalica',  16,  0.9,  3.6,  0.1,  0.5,  100),
('Cenoura crua',                      'hortalica',  34,  1.3,  7.7,  0.2,  3.2,  100),
('Beterraba cozida',                  'hortalica',  32,  1.3,  7.2,  0.1,  1.9,  100),
('Abobrinha cozida',                  'hortalica',  15,  1.1,  3.0,  0.2,  1.3,  100),
('Abóbora cabotiá cozida',            'hortalica',  48,  1.4,  12.0, 0.4,  2.5,  100),
('Berinjela cozida',                  'hortalica',  19,  0.7,  4.4,  0.1,  2.5,  100),
('Chuchu cozido',                     'hortalica',  19,  0.4,  4.8,  0.1,  1.0,  100),
('Vagem cozida',                      'hortalica',  25,  1.8,  5.3,  0.2,  2.4,  100),
('Quiabo cozido',                     'hortalica',  30,  1.9,  6.4,  0.3,  3.2,  100),
('Pimentão verde',                    'hortalica',  21,  1.1,  4.9,  0.2,  2.6,  100),
('Pimentão vermelho',                 'hortalica',  31,  1.0,  6.0,  0.3,  2.1,  100),
('Cebola',                            'hortalica',  40,  1.7,  8.9,  0.1,  2.2,  100),
('Alho',                              'hortalica',  113, 7.0,  23.9, 0.2,  4.3,  10),
('Palmito em conserva',               'hortalica',  20,  2.5,  2.6,  0.4,  2.6,  100),
('Cogumelo champignon',               'hortalica',  22,  2.1,  2.8,  0.5,  1.0,  100),
('Aspargos cozidos',                  'hortalica',  22,  2.4,  4.1,  0.2,  2.0,  100),

-- Bebidas
('Água de coco',                      'bebida',     22,  0.0,  5.3,  0.0,  0.1,  200),
('Café sem açúcar',                   'bebida',     2,   0.2,  0.3,  0.0,  0.0,  200),
('Chá verde sem açúcar',              'bebida',     1,   0.0,  0.2,  0.0,  0.0,  200),
('Suco de laranja natural',           'bebida',     45,  0.7,  10.4, 0.2,  0.2,  200),
('Suco de uva integral',              'bebida',     60,  0.4,  15.0, 0.1,  0.2,  200),
('Isotônico',                         'bebida',     26,  0.0,  6.4,  0.0,  0.0,  500),

-- Suplementos
('Whey protein (pó)',                 'suplemento', 380, 75.0, 7.0,  5.0,  0.0,  30),
('Whey isolado (pó)',                 'suplemento', 370, 85.0, 3.0,  1.0,  0.0,  30),
('Caseína (pó)',                      'suplemento', 360, 78.0, 6.0,  2.0,  0.0,  30),
('Albumina (pó)',                     'suplemento', 375, 80.0, 5.0,  1.0,  0.0,  30),
('Proteína vegetal (pó)',             'suplemento', 375, 80.0, 5.0,  3.0,  2.0,  30),
('Colágeno hidrolisado (pó)',         'suplemento', 360, 90.0, 0.0,  0.0,  0.0,  10),
('Creatina monoidratada',             'suplemento', 0,   0.0,  0.0,  0.0,  0.0,  5),
('Maltodextrina',                     'suplemento', 380, 0.0,  95.0, 0.0,  0.0,  30),
('Dextrose',                          'suplemento', 380, 0.0,  95.0, 0.0,  0.0,  30),
('Barra de proteína',                 'suplemento', 350, 25.0, 40.0, 10.0, 3.0,  50)
) as v(name, category, calories, protein, carbs, fat, fiber, serving_size)
where not exists (select 1 from foods t where t.name = v.name);

-- Seed: catálogo de exercícios
--
-- 181 exercícios, classificados em três eixos: `muscle_group` diz onde no
-- corpo, `venue` diz onde dá para executar, `category` diz que trabalho é.
-- As colunas nascem na migration 0042, que roda antes deste arquivo tanto no
-- `db reset` local quanto no workflow (db push, depois este seed).
--
-- Mesmo guard `where not exists` do resto: re-executar não duplica, e uma
-- linha que já existe não é tocada — a classificação das que vieram antes da
-- 0042 é responsabilidade do UPDATE que mora lá.

insert into exercises (name, muscle_group, venue, category, is_verified)
select v.name, v.muscle_group, v.venue, v.category, true
from (values
-- Peito
('Supino reto com barra',                  'peito',   'academia', 'forca'),
('Supino inclinado com halteres',          'peito',   'academia', 'forca'),
('Crucifixo com halteres',                 'peito',   'academia', 'forca'),
('Crossover no cabo',                      'peito',   'academia', 'forca'),
('Supino declinado',                       'peito',   'academia', 'forca'),
('Supino reto com halteres',               'peito',   'academia', 'forca'),
('Supino inclinado com barra',             'peito',   'academia', 'forca'),
('Voador (peck deck)',                     'peito',   'academia', 'forca'),
('Crossover no cabo baixo',                'peito',   'academia', 'forca'),
('Supino na máquina articulada',           'peito',   'academia', 'forca'),
('Flexão de braço',                        'peito',   'ambos',    'forca'),
('Flexão de braço com joelhos apoiados',   'peito',   'casa',     'forca'),
('Flexão de braço inclinada',              'peito',   'casa',     'forca'),
('Flexão de braço declinada',              'peito',   'casa',     'forca'),
('Flexão diamante',                        'peito',   'casa',     'forca'),
('Flexão com elástico',                    'peito',   'casa',     'forca'),
('Crucifixo com elástico em pé',           'peito',   'casa',     'forca'),
('Supino com elástico deitado',            'peito',   'casa',     'forca'),

-- Costas
('Puxada frontal',                         'costas',  'academia', 'forca'),
('Remada curvada com barra',               'costas',  'academia', 'forca'),
('Remada unilateral com halter',           'costas',  'academia', 'forca'),
('Levantamento terra',                     'costas',  'academia', 'forca'),
('Pull-up (barra fixa)',                   'costas',  'academia', 'forca'),
('Remada no cabo sentado',                 'costas',  'academia', 'forca'),
('Pullover com halter',                    'costas',  'academia', 'forca'),
('Puxada supinada',                        'costas',  'academia', 'forca'),
('Puxada com pegada neutra',               'costas',  'academia', 'forca'),
('Remada cavalinho',                       'costas',  'academia', 'forca'),
('Remada na máquina',                      'costas',  'academia', 'forca'),
('Levantamento terra romeno',              'costas',  'academia', 'forca'),
('Pulldown com braços estendidos',         'costas',  'academia', 'forca'),
('Barra fixa com pegada supinada',         'costas',  'academia', 'forca'),
('Remada invertida na barra baixa',        'costas',  'ambos',    'forca'),
('Remada curvada com elástico',            'costas',  'casa',     'forca'),
('Remada sentada com elástico',            'costas',  'casa',     'forca'),
('Puxada alta com elástico',               'costas',  'casa',     'forca'),
('Remada unilateral com mochila',          'costas',  'casa',     'forca'),

-- Ombro
('Desenvolvimento com barra',              'ombro',   'academia', 'forca'),
('Elevação lateral com halteres',          'ombro',   'academia', 'forca'),
('Elevação frontal',                       'ombro',   'academia', 'forca'),
('Desenvolvimento Arnold',                 'ombro',   'academia', 'forca'),
('Encolhimento de ombros',                 'ombro',   'academia', 'forca'),
('Face pull no cabo',                      'ombro',   'academia', 'forca'),
('Desenvolvimento com halteres sentado',   'ombro',   'academia', 'forca'),
('Elevação lateral no cabo',               'ombro',   'academia', 'forca'),
('Remada alta com barra',                  'ombro',   'academia', 'forca'),
('Crucifixo inverso na máquina',           'ombro',   'academia', 'forca'),
('Desenvolvimento na máquina',             'ombro',   'academia', 'forca'),
('Elevação lateral com elástico',          'ombro',   'casa',     'forca'),
('Desenvolvimento com elástico',           'ombro',   'casa',     'forca'),
('Flexão pique (pike push-up)',            'ombro',   'casa',     'forca'),

-- Ombro — manguito rotador e estabilizadores da escápula
('Rotação externa com elástico',           'ombro',   'ambos',    'estabilizacao'),
('Rotação interna com elástico',           'ombro',   'ambos',    'estabilizacao'),
('Rotação externa deitado de lado',        'ombro',   'ambos',    'estabilizacao'),
('Elevação em Y no banco inclinado',       'ombro',   'academia', 'estabilizacao'),
('Elevação no plano escapular',            'ombro',   'ambos',    'estabilizacao'),
('Face pull com elástico',                 'ombro',   'ambos',    'estabilizacao'),
('Punch do serrátil com elástico',         'ombro',   'ambos',    'estabilizacao'),
('Deslizamento do braço na parede',        'ombro',   'casa',     'estabilizacao'),
('Rotação com bastão acima da cabeça',     'ombro',   'ambos',    'mobilidade'),
('Círculos de braço',                      'ombro',   'casa',     'mobilidade'),

-- Bíceps
('Rosca direta com barra',                 'biceps',  'academia', 'forca'),
('Rosca alternada com halteres',           'biceps',  'academia', 'forca'),
('Rosca martelo',                          'biceps',  'academia', 'forca'),
('Rosca concentrada',                      'biceps',  'academia', 'forca'),
('Rosca no cabo',                          'biceps',  'academia', 'forca'),
('Rosca scott no banco',                   'biceps',  'academia', 'forca'),
('Rosca inversa com barra',                'biceps',  'academia', 'forca'),
('Rosca 21',                               'biceps',  'academia', 'forca'),
('Rosca direta com elástico',              'biceps',  'casa',     'forca'),
('Rosca martelo com elástico',             'biceps',  'casa',     'forca'),

-- Tríceps
('Tríceps testa com barra W',              'triceps', 'academia', 'forca'),
('Tríceps pulley corda',                   'triceps', 'academia', 'forca'),
('Tríceps coice com halter',               'triceps', 'academia', 'forca'),
('Mergulho entre bancos',                  'triceps', 'ambos',    'forca'),
('Tríceps francês',                        'triceps', 'academia', 'forca'),
('Tríceps pulley barra reta',              'triceps', 'academia', 'forca'),
('Paralelas',                              'triceps', 'academia', 'forca'),
('Tríceps acima da cabeça com elástico',   'triceps', 'casa',     'forca'),
('Tríceps coice com elástico',             'triceps', 'casa',     'forca'),

-- Pernas
('Agachamento livre',                      'pernas',  'academia', 'forca'),
('Leg press 45°',                          'pernas',  'academia', 'forca'),
('Cadeira extensora',                      'pernas',  'academia', 'forca'),
('Mesa flexora',                           'pernas',  'academia', 'forca'),
('Agachamento búlgaro',                    'pernas',  'ambos',    'forca'),
('Afundo com halteres',                    'pernas',  'academia', 'forca'),
('Stiff com barra',                        'pernas',  'academia', 'forca'),
('Cadeira abdutora',                       'pernas',  'academia', 'forca'),
('Cadeira adutora',                        'pernas',  'academia', 'forca'),
('Panturrilha em pé',                      'pernas',  'academia', 'forca'),
('Panturrilha sentado',                    'pernas',  'academia', 'forca'),
('Hack squat',                             'pernas',  'academia', 'forca'),
('Agachamento frontal',                    'pernas',  'academia', 'forca'),
('Agachamento no Smith',                   'pernas',  'academia', 'forca'),
('Levantamento terra sumô',                'pernas',  'academia', 'forca'),
('Passada com halteres',                   'pernas',  'academia', 'forca'),
('Panturrilha no leg press',               'pernas',  'academia', 'forca'),
('Bom dia com barra',                      'pernas',  'academia', 'forca'),
('Agachamento livre sem peso',             'pernas',  'casa',     'forca'),
('Agachamento com salto',                  'pernas',  'casa',     'forca'),
('Afundo estático sem peso',               'pernas',  'casa',     'forca'),
('Agachamento sumô sem peso',              'pernas',  'casa',     'forca'),
('Cadeira na parede',                      'pernas',  'casa',     'forca'),
('Panturrilha em pé no degrau',            'pernas',  'ambos',    'forca'),
('Stiff unilateral sem peso',              'pernas',  'casa',     'forca'),
('Subida no banco',                        'pernas',  'ambos',    'forca'),
('Agachamento com elástico',               'pernas',  'casa',     'forca'),

-- Glúteos
('Hip thrust com barra',                   'gluteos', 'academia', 'forca'),
('Elevação pélvica',                       'gluteos', 'ambos',    'forca'),
('Glúteo no cabo',                         'gluteos', 'academia', 'forca'),
('Agachamento sumô',                       'gluteos', 'academia', 'forca'),
('Coice de glúteo na máquina',             'gluteos', 'academia', 'forca'),
('Abdução de quadril no cabo',             'gluteos', 'academia', 'forca'),
('Ponte de glúteo no solo',                'gluteos', 'casa',     'forca'),
('Ponte de glúteo unilateral',             'gluteos', 'casa',     'forca'),
('Concha com elástico',                    'gluteos', 'ambos',    'estabilizacao'),
('Abdução deitado de lado',                'gluteos', 'casa',     'estabilizacao'),
('Caminhada lateral com elástico',         'gluteos', 'ambos',    'estabilizacao'),
('Coice de glúteo em quatro apoios',       'gluteos', 'casa',     'estabilizacao'),
('Abdução em quatro apoios',               'gluteos', 'casa',     'estabilizacao'),

-- Abdômen e core
('Abdominal crunch',                       'abdomen', 'ambos',    'forca'),
('Prancha',                                'abdomen', 'ambos',    'estabilizacao'),
('Elevação de pernas',                     'abdomen', 'ambos',    'forca'),
('Abdominal bicicleta',                    'abdomen', 'ambos',    'forca'),
('Crunch no cabo',                         'abdomen', 'academia', 'forca'),
('Abdominal oblíquo',                      'abdomen', 'ambos',    'forca'),
('Prancha lateral',                        'abdomen', 'ambos',    'estabilizacao'),
('Prancha com toque no ombro',             'abdomen', 'ambos',    'estabilizacao'),
('Inseto morto (dead bug)',                'abdomen', 'ambos',    'estabilizacao'),
('Bird dog',                               'abdomen', 'ambos',    'estabilizacao'),
('Pallof press com elástico',              'abdomen', 'ambos',    'estabilizacao'),
('Hollow hold',                            'abdomen', 'ambos',    'estabilizacao'),
('Rollout na roda abdominal',              'abdomen', 'ambos',    'estabilizacao'),
('Prancha com elevação de perna',          'abdomen', 'ambos',    'estabilizacao'),
('Caminhada do fazendeiro',                'abdomen', 'academia', 'estabilizacao'),
('Escalador (mountain climber)',           'abdomen', 'casa',     'forca'),
('Elevação de pernas na barra fixa',       'abdomen', 'academia', 'forca'),
('Rotação russa',                          'abdomen', 'casa',     'forca'),

-- Cardio
('Esteira',                                'cardio',  'academia', 'cardio'),
('Bike ergométrica',                       'cardio',  'academia', 'cardio'),
('Elíptico',                               'cardio',  'academia', 'cardio'),
('Corda naval',                            'cardio',  'academia', 'cardio'),
('Burpee',                                 'cardio',  'ambos',    'cardio'),
('Polichinelo',                            'cardio',  'ambos',    'cardio'),
('Remo ergômetro',                         'cardio',  'academia', 'cardio'),
('Escada ergométrica',                     'cardio',  'academia', 'cardio'),
('Bicicleta de assalto',                   'cardio',  'academia', 'cardio'),
('Pular corda',                            'cardio',  'ambos',    'cardio'),
('Corrida no lugar',                       'cardio',  'casa',     'cardio'),
('Salto do patinador',                     'cardio',  'casa',     'cardio'),

-- Alongamento
('Alongamento de peitoral no batente',     'peito',   'ambos',    'alongamento'),
('Alongamento de dorsal suspenso',         'costas',  'ambos',    'alongamento'),
('Alongamento de lombar joelhos ao peito', 'costas',  'casa',     'alongamento'),
('Postura da criança',                     'costas',  'casa',     'alongamento'),
('Alongamento cervical lateral',           'costas',  'casa',     'alongamento'),
('Alongamento de deltoide cruzado',        'ombro',   'ambos',    'alongamento'),
('Alongamento de tríceps sobre a cabeça',  'triceps', 'ambos',    'alongamento'),
('Alongamento de bíceps na parede',        'biceps',  'ambos',    'alongamento'),
('Alongamento de isquiotibiais sentado',   'pernas',  'casa',     'alongamento'),
('Alongamento de quadríceps em pé',        'pernas',  'ambos',    'alongamento'),
('Alongamento de panturrilha na parede',   'pernas',  'ambos',    'alongamento'),
('Alongamento de adutores borboleta',      'pernas',  'casa',     'alongamento'),
('Alongamento de flexores do quadril',     'pernas',  'casa',     'alongamento'),
('Alongamento de glúteo figura quatro',    'gluteos', 'casa',     'alongamento'),
('Alongamento de piriforme sentado',       'gluteos', 'casa',     'alongamento'),

-- Mobilidade
('Gato e camelo',                          'costas',  'casa',     'mobilidade'),
('Rotação torácica deitado de lado',       'costas',  'casa',     'mobilidade'),
('Extensão torácica no rolo',              'costas',  'ambos',    'mobilidade'),
('Lagarta (inchworm)',                     'costas',  'casa',     'mobilidade'),
('Mobilidade de tornozelo na parede',      'pernas',  'casa',     'mobilidade'),
('Agachamento profundo com apoio',         'pernas',  'casa',     'mobilidade'),
('Círculos de quadril em quatro apoios',   'gluteos', 'casa',     'mobilidade'),
('Transição 90/90 de quadril',             'gluteos', 'casa',     'mobilidade'),

-- Postural
('Retração escapular deitado de bruços',   'costas',  'casa',     'postural'),
('Superman no solo',                       'costas',  'casa',     'postural'),
('Elevação em Y no solo',                  'costas',  'casa',     'postural'),
('Elevação em T no solo',                  'costas',  'casa',     'postural'),
('Elevação em W no solo',                  'costas',  'casa',     'postural'),
('Retração cervical',                      'costas',  'casa',     'postural'),
('Anjo na parede',                         'ombro',   'casa',     'postural'),
('Ponte de glúteo com elástico',           'gluteos', 'casa',     'postural')
) as v(name, muscle_group, venue, category)
where not exists (select 1 from exercises t where t.name = v.name);
