// Tipos gerados do banco pelo Supabase CLI (`npm run db:types`). Vivem em
// shared/ porque são a fonte única das duas plataformas: enquanto existiam só
// no web, o cliente do mobile era construído sem genérico e toda consulta de lá
// devolvia `any` — foi assim que as dívidas #7, #10, #40 e #44 nasceram.

// Tabela de permissões do CASL — fonte única das duas plataformas.
export * from "./auth/abilities";
export * from "./auth/authErrors";
export * from "./auth/password-policy";
export * from "./auth/totp";
export * from "./data/anamnesisAdaptive";
export * from "./data/anamnesisQuestions";
export type { Database, Json } from "./database/database.types";
export * from "./services/assessment/adaptiveAnamnesis.service";
export * from "./services/assessment/bodyScan.service";
export * from "./services/assessment/bodyScanDescricao";
export * from "./services/assessment/fluxoDoBodyScan";
export * from "./services/auth/auth.service";
export * from "./services/briefing/activity.service";
export * from "./services/briefing/briefing.service";
export * from "./services/gamification/gamification.service";
export * from "./services/health/health.service";
export * from "./services/nutrition/diarioAlimentar.service";
export * from "./services/nutrition/hidratacao.service";
export * from "./services/nutrition/nutrition.service";
export * from "./services/progress/measurement.service";
export * from "./services/progress/progress.service";
export * from "./services/students/specialistNote.service";
export * from "./services/students/students.service";
export * from "./services/workouts/cardioHistory.service";
export * from "./services/workouts/heartRateProfile.service";
export type { ResumoDaPeriodizacao } from "./services/workouts/resumoDasPeriodizacoes";
export type { CardioWindow } from "./services/workouts/sessoes";
export * from "./services/workouts/workouts.service";
export * from "./technique/agachamento";
export * from "./technique/diagnostico";
export * from "./technique/fatos";
export * from "./technique/gravacao";
export * from "./technique/varredura";
export * from "./types/activity.types";
export * from "./types/auth.types";
export * from "./types/bodyScan.types";
export * from "./types/briefing.types";
export * from "./types/gamification.types";
export * from "./types/health.types";
export * from "./types/nutrition.types";
export * from "./types/physicalAssessment.types";
export * from "./types/respostasDaNutricao.types";
export * from "./types/specialistNote.types";
export * from "./types/students.types";
export * from "./types/workouts.types";
export * from "./utils/anamnese";
export * from "./utils/anamnesisMeasurement";
export * from "./utils/bodyMeasurements";
export * from "./utils/calendario";
export * from "./utils/dailyActivity";
export * from "./utils/dateOnly";
export * from "./utils/diarioAlimentar";
export * from "./utils/heartRateZones";
export * from "./utils/mealsOfDay";
export * from "./utils/measurementForm";
export * from "./utils/nome";
export * from "./utils/nutritionPeriod";
export * from "./utils/periodizacao";
export * from "./utils/periodReport";
export * from "./utils/periodTrend";
export * from "./utils/postgrest";
export * from "./utils/preparo";
export * from "./utils/progressSummary";
export * from "./utils/pse";
export * from "./utils/readiness";
export * from "./utils/respostasDaNutricao";
export * from "./utils/sessao";
export * from "./utils/texto";
export * from "./utils/trainingProgress";
export * from "./utils/treino";
